### ISSUE TITLE
Allow image to be uploaded to the server

### ISSUE THREAD

**Issue by shyamal890** [benwinding/quill-image-compress#13]
Please allow for files to be uploaded to the server and only store link to the file in the image src

**Comment by benwinding** [comment]
Hi @shyamal890 ,
This doesn't make sense for this module, as I already told you in #12 
Please check out some of these links to learn how to upload images using quill:
- https://github.com/quilljs/quill/issues/1089 
- https://github.com/fxmontigny/quill-image-upload
- https://github.com/noeloconnell/quill-image-uploader
