### ISSUE TITLE
Editor loses focus when pasting

### ISSUE THREAD

**Issue by raw-brt** [benwinding/quill-image-compress#14]
Hi Ben,

When pasting text or an image, **editor loses focus and scrolls to the top**.

Maybe saving cursor position before handling the clipboard contents and then resetting it could make the trick.

Best,
Roberto.

**Comment by benwinding** [comment]
Thanks for reporting, 
But I can't seem to replicate the issue:

![Peek 2020-12-22 14-49](https://user-images.githubusercontent.com/11782590/102846767-c6ee7e80-4460-11eb-82e1-051b62b93ece.gif)

Can you give me some more info:
- Quill version
- Quill image compress version
- Browser type and version
- OS version

Alternatively, submit a PR with a fix, it's a fairly simple package.

Cheers,
Ben

**Comment by raw-brt** [comment]
Ben,

Sorry for the late reply. Christmas, trips and stuff!

Here's what I'm talking about:

https://user-images.githubusercontent.com/12975849/103099978-d7455b80-4610-11eb-963f-dafc40651f39.mov

Context:

"react-quill": "^1.3.5"
"quill-image-compress": "^1.2.11"
Chrome and Safari, last version both
MacOS Big Sur 11.1 (though i've experienced this since Catalina).

Hope it helps a little bit more.

Thank you again and Merry Christmas! :D

**Comment by raw-brt** [comment]
I've found out that it's a problem related to core quill, not your plugin.

Thank you either way!

**Comment by benwinding** [comment]
No worries, glad to here you got it sorted.
Merry Christmas! :christmas_tree:

**Comment by raw-brt** [comment]
Thank you! Wish you the same! :)
