### ISSUE TITLE
Problem when including via script tag

### ISSUE THREAD

**Issue by JohnArcher** [benwinding/quill-image-compress#2]
Hi there,

I want to use the lib the classic way (similar to https://github.com/kensnyder/quill-image-drop-module#script-tag) and include it via the script tag like so (I took the minified file from the dist folder):

`<script src="quill.imageCompressor.min.js"></script>`

Then I want to register the module:

`Quill.register('modules/imageCompress', ImageCompress);`

But this command leeds to this JavaScript error: `Uncaught ReferenceError: ImageCompress is not defined`

I assume the min file is not indented to be used this way!? If so would it be possible to provide a file that could be used like I would like to use it?

**Comment by JaxonWright** [comment]
This is how I got this way to work:
* Use the non-minified version within the src directory.
* Removed the last line of the js file (`export default imageCompressor`)
* 2nd parameter of the register needs to be `imageCompressor`.

**Comment by benwinding** [comment]
Hey guys,
This should be fixed in `1.1.2`, you can now use the library via a script tag
Cheers

**Comment by nickbe** [comment]
Same problem with 1.2.14. The online demo uses the demo.js without including imageCompressor.js explicitly.

The error I get is:
![image](https://user-images.githubusercontent.com/10890765/106011288-9da5bb80-60ba-11eb-8459-14d5d3605937.png)

**Comment by Francesco96it** [comment]
Same problem with latest version. Any solution?
