### ISSUE TITLE
Transparent images have a black background

### ISSUE THREAD

**Issue by LeeHanYeong** [benwinding/quill-image-compress#22]
When using the library using the script tag, if a PNG image with a transparent background is compressed into JPEG, the background becomes black instead of white
<img width="1004" alt="스크린샷 2021-12-06 오후 6 10 54" src="https://user-images.githubusercontent.com/3809066/144818994-4547c8aa-7249-4771-bcc3-9a4cca6c2278.png">
.

Below is the original image used.
![absoluteholistic_dog_B103DF01_thumb02](https://user-images.githubusercontent.com/3809066/144819057-e725798b-4665-42f9-bc62-e2799d81779b.png)

**Comment by benwinding** [comment]
Yes this has been an annoying issue for a while, thanks @LeeHanYeong! 👍 

Closed by your PR #23
