### ISSUE TITLE
Demo and current package version throw an error

### ISSUE THREAD

**Issue by AndrewLester** [benwinding/quill-image-compress#25]
They're throwing an error on this line:
https://github.com/benwinding/quill-image-compress/blob/b11125f45435739a790d0a38b68f2bbea3e4b437/src/downscaleImage.js#L49
The error is presumably due to `ignoreImageTypes` being undefined, so it may also occur because `keepImageTypes` could be undefined too?

Workaround:
Set `ignoreImageTypes` and `keepImageTypes` to empty arrays in the config.

**Comment by benwinding** [comment]
Thanks for reporting @AndrewLester, that was a recent change (2 days ago) Thanks for the work around, I'll put the fix in now

**Comment by AndrewLester** [comment]
Thanks for the quick reply, the package works flawlessly otherwise.
