### ISSUE TITLE
Pasted images aren't being compressed

### ISSUE THREAD

**Issue by Arthur-o-b** [benwinding/quill-image-compress#26]
Hey, love the package, it's been really useful in a project i'm currently working on.

I've been having an issue with inconsistent compressing while pasting images, i'm not too sure of how it works even after testing it for a while.
From what i've gathered, the image is only being compressed on paste if it also needs resizing.

Eg.: Using a quality of 0.1 (for exaggeration) with 1k x 1k size limit
If an image of 999 x 999 is pasted, it will keep it's original size and quality
If an image of 1001 x 1001 is pasted, it will be resized down and be compressed

It only seems to affect paste and not the other insertion methods.

image for context:
![image](https://user-images.githubusercontent.com/61844053/148234589-ebb2d393-86e2-433a-b8b6-c4a21396f111.png)

Even if this can't be helped, the package is already a BIG BIG help, so thanks anyways!

**Comment by benwinding** [comment]
Hi @Arthur-o-b,
Thanks for reporting this. Yes you are correct, the images are not processed if the size is not within the config limits, but I think they should be (as that's what this library is meant to do!).
Should be an easy fix, will have a look at one today 👍

**Comment by benwinding** [comment]
Hi @Arthur-o-b,
Try version `quill-image-compress@1.2.21` and see if that works a bit better.
There was some complexity when pasting from word documents, but it's probably not required anymore and is handled elsewhere.

**Comment by Arthur-o-b** [comment]
Hey, @benwinding just finished running my tests.
Works like a charm!

Thanks again for this 👍
