### ISSUE TITLE
maxWidth: smaller images are enlarged

### ISSUE THREAD

**Issue by abruegit** [benwinding/quill-image-compress#3]
Expected behaviour: smaller images should keep their dimensions.
Observed behaviour: smaller images are enlarged to maxWidth.

**Comment by benwinding** [comment]
Hi @abruegit,

This was an issue in previous versions, would you be able to check with version `1.1.2`?

Let me know.

Cheers,
Ben

**Comment by abruegit** [comment]
Hi Ben,

Oh I see, awesome, thanks! Works perfectly.
I was also wondering if you could add max-height?
e.g. max-width: 800, max-height: 800 --> if the image is 1000x4000 it should be 200x800, not 800x2400.

Cheers,
Andrea



Andrea 
Brühlmann
Anwendungsentwicklerin
DV Bern AG | Nussbaumstrasse 21 | Postfach 106 | CH-3000 
Bern 22
T +41 31 378 24 24 | D +41 31 378 24 87
www.dvbern.ch
Wir suchen Spezialisten, helfen Sie uns!  https://www.dvbern.ch/karriere
 
Von: Ben Winding <notifications@github.com>
Gesendet: Mittwoch, 6. November 2019 10:58
An: benwinding/quill-image-compress <quill-image-compress@noreply.github.com>
Cc: Brühlmann Andrea <andrea.bruehlmann@dvbern.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [benwinding/quill-image-compress] maxWidth: smaller images are enlarged (#3)


Hi @abruegit<https://github.com/abruegit>,

This was an issue in previous versions, would you be able to check with version 1.1.2?

Let me know.

Cheers,
Ben

**Comment by benwinding** [comment]
Hey @abruegit ,

Try version: **quill-image-compress@1.2.0** you can now use the option `maxHeight` as well!

Cheers,
Ben

**Comment by abruegit** [comment]
Hi Ben,

You are very fast, thank you very much!
Just a little code review:
I think you missed the case when both input width and height are bigger than the max dimensions and the height is bigger than the width. I suggest the following code:


function getDimensions(inputWidth, inputHeight, maxWidth, maxHeight) {
  if (inputWidth < maxWidth && inputHeight < maxHeight) {
    return [inputWidth, inputHeight];
  }
  if (inputWidth > maxWidth) {
    const newWidth = maxWidth;
    const newHeight = Math.floor((inputHeight / inputWidth) * newWidth);

    if (newHeight > maxHeight) {
        const newHeight = maxHeight;
        const newWidth = Math.floor((inputWidth / inputHeight) * newHeight);
        return [newWidth, newHeight];
    }
    else {
        return [newWidth, newHeight];
    }
  }
  if (inputHeight > maxHeight) {
    const newHeight = maxHeight;
    const newWidth = Math.floor((inputWidth / inputHeight) * newHeight);
    return [newWidth, newHeight];
  }
}

Regards,
Andrea



Andrea 
Brühlmann
Anwendungsentwicklerin
DV Bern AG | Nussbaumstrasse 21 | Postfach 106 | CH-3000 
Bern 22
T +41 31 378 24 24 | D +41 31 378 24 87
www.dvbern.ch
Wir suchen Spezialisten, helfen Sie uns!  https://www.dvbern.ch/karriere
 
Von: Ben Winding <notifications@github.com>
Gesendet: Donnerstag, 7. November 2019 08:05
An: benwinding/quill-image-compress <quill-image-compress@noreply.github.com>
Cc: Brühlmann Andrea <andrea.bruehlmann@dvbern.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [benwinding/quill-image-compress] maxWidth: smaller images are enlarged (#3)


Hey @abruegit<https://github.com/abruegit> ,

Try version: quill-image-compress@1.2.0 you can now use the option maxHeight as well!

Cheers,
Ben

**Comment by abruegit** [comment]
Hey Ben,

Do you think it would be possible to add the imageCompress functionality to image drop as well? I was trying to use the imageDrop module to allow copy+paste but then the original images are inserted. If imageCompress could handle that case as well that would be genious.

Cheers,
Andrea




Andrea 
Brühlmann
Anwendungsentwicklerin
DV Bern AG | Nussbaumstrasse 21 | Postfach 106 | CH-3000 
Bern 22
T +41 31 378 24 24 | D +41 31 378 24 87
www.dvbern.ch
Wir suchen Spezialisten, helfen Sie uns!  https://www.dvbern.ch/karriere
 
Von: Ben Winding <notifications@github.com>
Gesendet: Donnerstag, 7. November 2019 08:05
An: benwinding/quill-image-compress <quill-image-compress@noreply.github.com>
Cc: Brühlmann Andrea <andrea.bruehlmann@dvbern.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [benwinding/quill-image-compress] maxWidth: smaller images are enlarged (#3)


Hey @abruegit<https://github.com/abruegit> ,

Try version: quill-image-compress@1.2.0 you can now use the option maxHeight as well!

Cheers,
Ben

**Comment by benwinding** [comment]
Hi @abruegit,

Thanks for that fix, it's been added here: a9cd8fbac6c53593ff7d7620bff016bf05bac821

Demo site is here: https://benwinding.github.io/quill-image-compress/src/demo.html

And deployed to npm as version 1.2.2

Cheers,
Ben

**Comment by benwinding** [comment]
I've added a new issue https://github.com/benwinding/quill-image-compress/issues/4, for the integration of quill-image-drop-module, please see that issue for further information
