### ISSUE TITLE
console error: Logger is not defined

### ISSUE THREAD

**Issue by Himanshu-Negi-Dev** [benwinding/quill-image-compress#33]
Hey! @benwinding @LeeHanYeong @koenvg 
i am using quill-image-compress version 1.2.15 with react-quill its working fine, But when i upgarded quill-image-compress to version 1.2.23 my whole application is breaking and its giving error on console "Logger is not defined"

![Screenshot from 2022-05-19 16-32-06](https://user-images.githubusercontent.com/80190920/169278893-32f9ec28-12b5-45ab-b83b-1d0db8b20ffd.png)

here the screen shot of error

I also checked in node_modules in version 1.2.15 there's file in node_modules/quill-image-compress folder called quill-imagecompress.js but in version 1.2.23 there no such file 

i also have an error in my import line 
![Screenshot from 2022-05-19 16-40-34](https://user-images.githubusercontent.com/80190920/169280508-258ff363-0d6d-4b24-8faf-51f641026fc1.png)
Here the screen shot for that

**Comment by benwinding** [comment]
Thanks for reporting @Himanshu-Negi-Dev,
Should be fixed now 👌
