### ISSUE TITLE
Issue with Double Image Display in Quill Editor After Pasting

### ISSUE THREAD

**Issue by luc345** [benwinding/quill-image-compress#51]
Environment: Next.js 14.2.4, quill-image-compress 1.2.33, Quill 2.0.2

Description:
After pasting an image into the editor, I expect to see only the processed image; however, the editor displays both the original and the processed images. 

Console Output:
- quill-image-compress: handleDataTransferList {fileTypes: Array(2), imageCount: 1}
- quill.imageCompressor.min.js:1 quill-image-compress: pasteFilesIntoQuill pasting 1 images...
- quill.imageCompressor.min.js:1 quill-image-compress: pasteFilesIntoQuill pasting image (0)
- quill.imageCompressor.min.js:1 quill-image-compress: onImageDrop {dataUrl: 'data:image/png;base64,...
- quill.imageCompressor.min.js:1 quill-image-compress: pasteFilesIntoQuill done
- quill.imageCompressor.min.js:1 quill-image-compress: downscaling image... {args: {...}, newHeight: 4...
- quill.imageCompressor.min.js:1 quill-image-compress: downscaleImageFromUrl {dataUrl: 'data:image/png;ba...
- quill.imageCompressor.min.js:1 quill-image-compress: insertToEditor {url: 'data:image/png;base64,...'}
- quill.imageCompressor.min.js:1 quill-image-compress: estimated img size: 480 kb

When using the toolbar to upload images, the feature works as expected, displaying only one processed image.

Thank you for your assistance.

**Comment by enzedonline** [comment]
Do you have anything else with an event listener on paste? I'm using quill-paste=smart and see this when I run the two together. One is the image with url src, the other with the compressed data src.

I'm thinking I need to create my own fork that can disable onPaste handling in imageCompress and handle that externally. It's possible to get the compressed dataURL from `quill.getModule('imageCompressor').downscaleImageFromUrl(yourDataURL)`.

Could be added as a module option (e.g. disableOnPaste)

```javascript
    imageCompress: {
      disableOnPaste: true;
    }
```

I could make this a PR if others are interested. Not sure if this is still maintained.

**Comment by enzedonline** [comment]
I've made a pull request (#53), adds `handleOnPaste` to the options. If set to false, the paste event listener is not added to the quill root.

**Comment by benwinding** [comment]
Thanks for fixing @enzedonline 🙏 
Released as version `2.0.1`

**Comment by luc345** [comment]
@enzedonline Sorry for seeing your reply late.
Thanks @enzedonline @benwinding🙏

**Comment by luc345** [comment]
@enzedonline  I tested the new version and found that setting handleOnPaste: false resolves the issue with pasting images. However, the problem still occurs when images are dragged directly into the editor. By 'dragging', I mean clicking on an image with the left mouse button and holding it down to move it into the editor, rather than using right-click to copy and paste.

If you're willing, could you please test it further? I would greatly appreciate it.

**Comment by enzedonline** [comment]
@luc345 The [change](https://github.com/benwinding/quill-image-compress/blob/9c1a4d3d43d11b5bf7b998834e7881ac4c7bfd23/src/quill.imageDrop.ts#L22) I made was specifically for the paste event:

```js
    // listen for drop and paste events
    this.quill.root.addEventListener("dragstart", (e) => this.handleDragStart(e), false);
    this.quill.root.addEventListener("dragend", (e) => this.handleDragEnd(e), false);
    this.quill.root.addEventListener("drop", (e) => this.handleDrop(e), false);
    if (this.handleOnPaste) {
      this.quill.root.addEventListener(
        "paste",
        (e) => this.handlePaste(e),
        false
      );
    }
```
Do you have any other quill modules that listen for drop events? (e.g. quill-image-drop-module). Might be worth looking on the dev tools window and see if there are multiple event listeners for drop.

I see the following on mine (uploader.ts is the Quill native handler):
![image](https://github.com/user-attachments/assets/a178c246-2fb9-4621-8c56-2886aa7f9642)

I'm not seeing double handling on image drop.

**Comment by luc345** [comment]
@enzedonline Thank you for your reply. 

I am not using any other Quill drag-and-drop modules. If I drag an image from a web page into the editor, it displays a processed image as expected. However, if I drag an image from my computer desktop into the editor, it results in two images being displayed: one original and one processed. 

Currently, I am using e.preventDefault(); e.stopPropagation(); to completely block image dragging in my project. Although this is not the ideal solution, it at least prevents confusion for the users.

**Comment by enzedonline** [comment]
Ah, ok, I see that now. I'd misunderstood the original issue. The first image is the original, the second is the compressed image. It also double pastes from the file system if I copy/paste from the the file explorer. 

![image](https://github.com/user-attachments/assets/b9d35010-7b85-4418-8d15-0aa154772d91)

It's replicated in the [code pen here](https://codepen.io/enzedonline/pen/gONrmBX?editors=0011).

Weirdly, if I run the project in dev mode and use the demo or demo-script-tag page, it doesn't double-handle for either drag or paste.

I think I have it fixed by setting `true` on the event listener `option` parameter and using `evt.stopPropagation()` in the handlers.

Could you test with the minified js? You can download from [here](https://1drv.ms/u/s!AppilyLm3gHit50pA6NFi-Wm4n8RyQ?e=xbvncq), or you can grab the modified code for ImageDrop from https://github.com/enzedonline/quill-image-compress/blob/master/src/quill.imageDrop.ts

**Comment by luc345** [comment]
I tested the code and it successfully solved my problem. Thank you for your help!

**Comment by luc345** [comment]
@enzedonline  I tested the code and it successfully solved my problem. Thank you for your help!

**Comment by enzedonline** [comment]
> @enzedonline I tested the code and it successfully solved my problem. Thank you for your help!

Great :) Which OS did you test with? I haven't tested this with Mac or Linux.

**Comment by luc345** [comment]
I've only tested it on Windows so far 😁. I'll come back and share if I test it on other operating systems in the future.

**Comment by enzedonline** [comment]
I was thinking of testing on other OS's before making this a PR ... 😉

**Comment by enzedonline** [comment]
I thought I might have broken image drop on Firefox, but tested on the old version and it doesn't work there either. The data types are all '-moz-' types. Probably needs separate handling ... I'm not touching that 😂too much other stuff on.

**Comment by bacinet02** [comment]
Hello,
I have the same problem on Linux with Firefox.
I'm using version 2.0.2 of quill and quill-image-compress.

:-)

**Comment by marcramser** [comment]
Same here also with 2.0.2 Windows and Chrome (also other browsers)

**Comment by marcramser** [comment]
@enzedonline 

I’m having the same issue. Turning off compression when pasting does help with the problem, but it also stops the compression feature from working on paste, which seems like it defeats the point of using a compression plugin.

In older versions, this worked fine, so IMHO would be better to fix the root of the problem rather than cover it up. Or am I missing an important detail here?

Looking forward to any updates or fixes. Thanks!

**Comment by OoKyleoO** [comment]
@enzedonline Hi I can test it on mac, but I dont know how to generate the  min.js files. ><

**Comment by OoKyleoO** [comment]
@enzedonline Hi I've manually downloaded the source code and intergrated in my project. Works fine on Mac. THX!!!
please let me know if there's a release on npm.

**Comment by marcramser** [comment]
I would also be very interested in this fix.

**Comment by enzedonline** [comment]
@OoKyleoO It's not my package to publish, it's up to @benwinding 

@bacinet02 did you test the code from my repository ([link](https://github.com/enzedonline/quill-image-compress/blob/master/src/))? Interested to know if it works with Linux/Firefox. The image doesn't paste at all with windows/firefox when copying from the file system, but this is for all versions.
