### ISSUE TITLE
Drag and Drop Support

### ISSUE THREAD

**Issue by pmaddaloni-shujinko** [benwinding/quill-image-compress#8]
~~It'd be great to see some sort of support for GIFs, whether that's via compressing them, or just taking the first frame of a GIF and inserting that instead of the whole GIF. Thanks so much for your work!~~

EDIT: Turns out it's an issue of drag and drop not utilizing this module, not that GIFs aren't supported. My mistake! Any change we could get drag and drop support? Thank you again!

**Comment by Mr-MooMoo** [comment]
+1 That would be perfect!

**Comment by benwinding** [comment]
Finally done, let me know how it goes!
